name: Paso 0 # Iniciar ejercicio

on:
  push:
    branches:
      - main

permissions:
  contents: write # Actualizar Readme
  actions: write # Deshabilitar/habilitar workflows
  issues: write # Crear issue y comentar en issues


env:
  STEP_1_FILE: ".github/steps/1-implementa-cuadrantes.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Iniciar ejercicio
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.4.0
    with:
      exercise-title: "Introducción a GitHub"
      intro-message: "Si eres nuevo en GitHub, notarás que otros desarrolladores usan ___**issues**___ para organizar su trabajo y colaborar. ¡Nosotros haremos lo mismo!"


  post_next_step_content:
    name: Publicar contenido del siguiente paso
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_URL: ${{ needs.start_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtener plantillas de respuesta
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.0

      - name: Crear comentario - agregar contenido del paso
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.STEP_1_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Crear comentario - esperando progreso
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deshabilitar workflow actual y habilitar el siguiente
        run: |
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
